site_name: Kumodd - Google Drive Forensics
site_description: Kumodd - Google Drive Forensics
site_author: Rich Murphey
copyright: (C) 2019 Rich Murphey
pages:
- ['Home.md', 'Overview']
- ['How-to-Use-Kumodd.md', 'Usage Examples']
- ['How-to-Install.md', 'How to Install']
- ['How-to-Configure.md', 'How to Configure']
- ['Default-configuration.md', 'Default Configuration']
- ['Metadata.md', 'Google Drive Metadata']
- ['Search-Query.md', 'How to Search for Files']
- ['Methods.md', 'Data Verification Methods']
- ['How-to-Verify-Data.md', 'How to Verify Files']
- ['Log2Timeline-Export.md', 'Log2Timeline Export']
- ['Command-line-options.md', 'Command Line Options']
- ['How-to-Test-Kumodd.md', 'How to Test Kumodd']
- ['How-to-Build.md', 'How to Build']
- ['Example-Metadata.md', 'Example Metadata']
- ['Limitations.md', 'Limitations']
- ['References.md', 'References']
