site_name: Kumodd
site_description: Kumodd - Google Drive Forensics
site_author: Rich Murphey
copyright: Copyright &copy; 2019 Caery Richard Murphey
repo_url: https://github.com/
edit_uri: ""
plugins:
    - search
theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - python
markdown_extensions:
    - toc:
        permalink: True
    - smarty
    - admonition
    - def_list

nav:
    - Home: Home.md
    - User Guide:
        - Usage Examples: guide/How-to-Use-Kumodd.md
        - How to Install: guide/How-to-Install.md
        - How to Configure: guide/How-to-Configure.md
        - Default Configuration: guide/Default-configuration.md
        - Google Drive Metadata: guide/Metadata.md
        - How to Search for Files: guide/Search-Query.md
        - Data Verification Methods: guide/Methods.md
        - How to Verify Files: guide/How-to-Verify-Data.md
        - Log2Timeline Export: guide/Log2Timeline-Export.md
        - Command Line Options: guide/Command-line-options.md
        - How to Test Kumodd: guide/How-to-Test-Kumodd.md
        - Example Metadata: guide/Example-Metadata.md
        - References: guide/References.md
    - Developers:
        - How to Build: devel/How-to-Build.md
        - Limitations: devel/Limitations.md
